name: Auto-Doc Generator

on:
  workflow_dispatch:  # allows manual trigger from GitHub UI
  push:
    paths:
      - '**'
  pull_request:
    paths:
      - '**'

permissions:
  contents: write  # needed to push commits back to the repo

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install openai difflib

      - name: Run Doc Generator
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python .github/scripts/gen_doc.py

      - name: Commit changes
        run: |
          git config user.name "doc-bot"
          git config user.email "doc-bot@ortwmailserver.com"
          git add docs/docAid.md
          git commit -m "Update documentation [auto]"
          git push

